{
 "title": "Zeebe",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing per Partition",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"processed\"}[5m])) by (pod, partition, processor, action)",
     "legendFormat": "{{pod}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Exporting per Partition",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (pod, partition, exporter)",
     "legendFormat": "{{pod}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Current Roles",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "atomix_role{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
     "legendFormat": "{{pod}} {{partitionGroupName}} {{partition}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - kube_pod_container_status_ready{pod=~\".*\", pod!~\"curator.*|worker.*|starter.*\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} restart"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_ready{container=\"worker\",namespace=\"$namespace\"}[1m])) or vector(1)",
     "legendFormat": "Worker restart"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_ready{container=\"starter\",namespace=\"$namespace\"}[1m])) or vector(1)",
     "legendFormat": "Starter Restart"
    }
   ]
  },
  {
   "title": "Partition health ",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "zeebe_health{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} {{partition}}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "table-old",
   "description": "Displays the current running pods in the namespace.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing per Partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written|processed\"}[5m])) by (pod, partition, processor, action)",
     "legendFormat": "{{pod}}-{{partition}}-{{processor}}-{{action}}"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (pod, partition, exporter)",
     "legendFormat": "{{pod}}-{{partition}}-{{exporter}}"
    }
   ]
  },
  {
   "title": "Completed Processes in avg overtime per sec",
   "type": "singlestat",
   "description": "Takes the avg of all completed processes per second over the given time range.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[5m]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Current Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (type, action)",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Completed Tasks in avg overtime per sec",
   "type": "singlestat",
   "description": "Takes the avg of all completed tasks per second over the given time range.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[5m]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Backpressure Dropping Requests [1m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(zeebe_dropped_request_count_total{namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) / sum(rate(zeebe_received_request_count_total{namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) ) * 100",
     "legendFormat": "Partition {{partition}}"
    },
    {}
   ]
  },
  {
   "title": "Number of records not processed",
   "type": "gauge",
   "description": "Shows how many records the stream processor has not processed yet.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zeebe_log_appender_last_committed_position{namespace=~\"$namespace\", partition=~\"$partition\"} - zeebe_stream_processor_last_processed_position{namespace=~\"$namespace\", partition=~\"$partition\"}",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Append Backpressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_deferred_append_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
     "legendFormat": "deferred-{{partition}}"
    },
    {
     "expr": "sum(rate(zeebe_try_to_append_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
     "legendFormat": "try-to-append-{{partition}}"
    },
    {
     "expr": "sum(zeebe_backpressure_append_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
     "legendFormat": "queue-limit-{{partition}}"
    },
    {
     "expr": "zeebe_backpressure_inflight_append_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"} ",
     "legendFormat": "Inflight-for-{{partition}}"
    }
   ]
  },
  {
   "title": "Command API Backpressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_dropped_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
     "legendFormat": "dropped-{{partition}}"
    },
    {
     "expr": "sum(rate(zeebe_received_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
     "legendFormat": "received-{{partition}}"
    },
    {
     "expr": "sum(zeebe_backpressure_requests_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
     "legendFormat": "queue-limit-{{partition}}"
    },
    {
     "expr": "zeebe_backpressure_inflight_requests_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}",
     "legendFormat": "inflight-{{partition}}"
    }
   ]
  },
  {
   "title": "GRPC Requests handled per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\"}[5m])) by (grpc_method)",
     "legendFormat": "{{grpc_method}} Request"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_started_total{namespace=~\"$namespace\"}[5m])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    },
    {
     "expr": "sum(rate(grpc_client_completed{namespace=~\"$namespace\"}[5m])) by (grpc_method, code)",
     "legendFormat": "{{grpc_method}} ({{code}})"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Number of records exported but not acknowledged",
   "type": "gauge",
   "description": "Shows how many positions are not updated by exporters per partition. Means what is the difference between last committed exporter position and committed log position.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zeebe_exporter_last_exported_position{namespace=~\"$namespace\", partition=~\"$partition\"} - zeebe_exporter_last_updated_exported_position{namespace=~\"$namespace\", partition=~\"$partition\"}",
     "legendFormat": "{{exporter}} {{partition}}"
    }
   ]
  },
  {
   "title": "Last appended position",
   "type": "table-old",
   "description": "Shows the position, which was appended last by the leader per partition.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (partition) (zeebe_log_appender_last_appended_position{namespace=~\"$namespace\", partition=~\"$partition\"})"
    }
   ]
  },
  {
   "title": "Last committed position",
   "type": "table-old",
   "description": "Shows the last committed log position.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum by (partition) (zeebe_log_appender_last_committed_position{namespace=~\"$namespace\", partition=~\"$partition\"})"
    }
   ]
  },
  {
   "title": "Last processed position",
   "type": "table-old",
   "description": "Shows the last processed position by the stream processor per partition.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 42 },
   "targets": [
    {
     "expr": "sum by (partition) (zeebe_stream_processor_last_processed_position{namespace=~\"$namespace\", partition=~\"$partition\"})"
    },
    {}
   ]
  },
  {
   "title": "Number of records not exported",
   "type": "gauge",
   "description": "Shows how many records are not exported yet.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (zeebe_log_appender_last_committed_position{namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition) - sum (zeebe_exporter_last_exported_position{namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"}) by (partition)",
     "legendFormat": "Exporter {{partition}}"
    }
   ]
  },
  {
   "title": "Last updated exported position",
   "type": "table-old",
   "description": "Shows the last exported position which was committed by the given exporter per partition.",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (exporter, partition) (zeebe_exporter_last_updated_exported_position{namespace=~\"$namespace\", partition=~\"$partition\"})"
    }
   ]
  },
  {
   "title": "Last exported position",
   "type": "table-old",
   "description": "Shows the last exported position per partition.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 46 },
   "targets": [
    {
     "expr": "sum by (partition) (zeebe_exporter_last_exported_position{namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"})"
    },
    {}
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Workflow Instance Events per second (range = 5m)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[5m])) by (action)\n"
    }
   ]
  },
  {
   "title": "Job events per second (range = 5m)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (action)",
     "legendFormat": "Stream Processor"
    }
   ]
  },
  {
   "title": "Workflow Instance Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  },
  {
   "title": "Workflow Instance Events per second (range = 5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[5m])) by (action)",
     "legendFormat": "Workflow Instance ({{action}})"
    },
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (action)",
     "legendFormat": "Job ({{action}})"
    }
   ]
  },
  {
   "title": "Stream Processor Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
     "legendFormat": "{{processor}} ({{action}})"
    },
    {
     "expr": "sum(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action, processor)",
     "legendFormat": "exporter ({{action}})"
    }
   ]
  },
  {
   "title": "Stream Processor Events per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_stream_processor_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (action, processor)",
     "legendFormat": "{{processor}} ({{action}})"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])) by (action, processor)",
     "legendFormat": "exporter ({{action}})"
    }
   ]
  },
  {
   "title": "Running Workflow Instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_running_workflow_instances_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
     "legendFormat": "Workflow Instance"
    },
    {
     "expr": "sum(zeebe_pending_jobs_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(zeebe_pending_incidents_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"})",
     "legendFormat": "Incidents"
    }
   ]
  },
  {
   "title": "Stream Processor vs Exporter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_stream_processor_events_total{namespace=~\"$namespace\", action=~\"skipped|processed\", partition=~\"$partition\", pod=~\"$pod\"}) - sum(zeebe_exporter_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"})",
     "legendFormat": "Events processed but not exported"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Count",
     "type": "graph",
     "description": "Total number of committed snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_snapshot_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[1m])",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Operation Duration",
     "type": "heatmap",
     "description": "Approximate duration of taking a single snapshot from the processor point-of-view (without replication or committing).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_duration_bucket{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Size",
     "type": "graph",
     "description": "Size in bytes of snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_size_bytes{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Files Sizes (1m)",
     "type": "heatmap",
     "description": "Distribution of snapshot file sizes - each snapshot may be comprised of many files, and this shows approximately how \"big\" files there are and how many \"small\" files.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_file_size_megabytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of files in a snapshot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_chunks_count{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "graph",
     "description": "Approximate duration of replicating a snapshot, from the receiver point-of-view.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_replication_duration_milliseconds{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "graph",
     "description": "On-going snapshot replications from the receiver point-of-view.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_replication_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Process memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=~\"$namespace\",pod=~\".*zeebe.*\", container=~\"zeebe.*\"}",
     "legendFormat": "{{pod}} RSS"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
     "legendFormat": "{{pod}} JVM heap"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Buffer Pool Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_buffer_pool_used_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,pool)",
     "legendFormat": "Used {{pod}}:{{pool}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\"} / process_max_fds{namespace=~\"$namespace\",pod=~\"$pod\"}) * 100",
     "legendFormat": "{{pod}} used fds"
    },
    {}
   ]
  },
  {
   "title": "PVC Disk Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "PVC Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Read bytes/s [1m]",
   "type": "graph",
   "description": "Shows the bytes read per second for the zeebe pods in the select namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Written bytes/s [1m]",
   "type": "graph",
   "description": "Shows the written bytes per second by the Zeebe pods in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network bytes/s transmitted [1m]",
   "type": "graph",
   "description": "Shows how many bytes the Zeebe Pods transmit per second in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network bytes/s received [1m]",
   "type": "graph",
   "description": "Shows how many bytes the Zeebe Pods have received per second in the selected namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$namespace.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Processing Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Processing Latency (Command)",
   "type": "heatmap",
   "description": "Shows the time (latency) between writing the command on the dispatcher and processing it.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"COMMAND\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing Latency (Event)",
   "type": "heatmap",
   "description": "Shows the time (latency) between writing the event on the dispatcher and processing it.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_stream_processor_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\", recordType=\"EVENT\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing Execution Time",
   "type": "heatmap",
   "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_workflow_instance_execution_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Activation Time",
   "type": "heatmap",
   "description": "Shows the time (latency) between creating the job and activating it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_job_activation_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Life Time",
   "type": "heatmap",
   "description": "Shows the complete lifetime of an job. This means the time (latency) between creating the job and completing it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_job_life_time_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "gRPC requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}) by (grpc_method, code)",
     "legendFormat": "{{grpc_method}} ({{code}})"
    }
   ]
  },
  {
   "title": "gRPC requests per second (range = 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (grpc_method, code)",
     "legendFormat": "{{grpc_method}} ({{code}})"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "Total requests completed"
    }
   ]
  },
  {
   "title": "Create Workflow Instance Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CreateWorkflowInstance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Activate Jobs Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 161 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"ActivateJobs\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Complete Job Latency (gRPC)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 161 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CompleteJob\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Gateway Request Latency",
   "type": "heatmap",
   "description": "Shows the latency (RTT) of a sent from the gateway to the broker.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum(increase(zeebe_gateway_request_latency_bucket{namespace=~\"$namespace\",partition=~\"$partition\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Failure Error Code",
   "type": "graph",
   "description": "Shows rate of each error type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(zeebe_gateway_failed_requests{namespace=~\"$namespace\", partition=~\"$partition\", error=~\".*\"}[5m]) / rate(zeebe_gateway_failed_requests{namespace=~\"$namespace\", partition=~\"$partition\"}[5m])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Failure Rate by Request Type",
   "type": "graph",
   "description": "Shows failure rate of requests sent from gateway to the broker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (requestType) (rate(zeebe_gateway_failed_requests{namespace=~\"$namespace\", partition=~\"$partition\"}[5m])) / \nsum by (requestType) (rate(zeebe_gateway_total_requests{namespace=~\"$namespace\", partition=~\"$partition\"}[5m]))",
     "legendFormat": "{{requestType}}"
    }
   ]
  },
  {
   "title": "Atomix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compacting time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(atomix_compaction_time_ms_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Creation Time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_creation_time_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "graph",
     "description": "Approximate Install RPC as measured by the follower.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_duration_milliseconds{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "graph",
     "description": "Ongoing snapshot replications per partition, from the follower point-of-view.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_count{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partitionGroupName}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_flush_time_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Append Entry Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(atomix_append_entries_latency_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Time Between Heartbeats",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_time_in_s_bucket{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heartbeat Miss Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_miss_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[1m])) by (pod, partition)",
       "legendFormat": "{{pod}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Role Changes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Role" }
     ],
     "targets": [
      {
       "expr": "atomix_role{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partition}} {{partitionGroupName}}"
      }
     ]
    },
    {
     "title": "Number of log segements",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_segment_count{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Commit Index",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 46 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_commit_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Commit Index",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "atomix_partition_raft_commit_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Commit Index",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "atomix_partition_raft_commit_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Index of last appended entry",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 51 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_append_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}-p{{partition}}"
      }
     ]
    },
    {
     "title": "Index of last appended entry",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 51 },
     "targets": [
      {
       "expr": "atomix_partition_raft_append_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}-p{{partition}}"
      }
     ]
    },
    {
     "title": "Index of last appended entry",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 51 },
     "targets": [
      {
       "expr": "atomix_partition_raft_append_index{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}-p{{partition}}"
      }
     ]
    },
    {
     "title": "Number of records appended on the leader but not committed",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "max(atomix_partition_raft_append_index{namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace) - max(atomix_partition_raft_commit_index{namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace)",
       "legendFormat": "Partition {{partition}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Number of records by which the slowest follower is lagging behind",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "max(atomix_partition_raft_commit_index{namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace) - min(atomix_partition_raft_commit_index{namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace)",
       "legendFormat": "Partition {{partition}} ({{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB Memory usage",
     "type": "graph",
     "description": "Sum of memtable, table reader and cache memory capacity.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum(zeebe_rocksdb_memory_estimate_table_readers_mem{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_size_all_mem_tables{namespace=~\"$namespace\",pod=~\"$pod\",  partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_block_cache_capacity{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition))",
       "legendFormat": "{{pod}} Table Reader {{partition}}"
      }
     ]
    },
    {
     "title": "Estimated Number of Keys",
     "type": "graph",
     "description": "Estimated total number of keys in the database per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_estimate_num_keys{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}} keys {{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Estimated Live Data",
     "type": "graph",
     "description": "Estimated amount of live data in bytes per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_live_estimate_live_data_size{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} live data {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. size of all mem tables",
     "type": "graph",
     "description": "Returns approximate size of active, unflushed immutable, and pinned immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L807",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_size_all_mem_tables{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} All Memtable's {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current all mem table size",
     "type": "graph",
     "description": "Approximate size of active and unflushed immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L803",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_all_mem_tables{namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current active mem table size",
     "type": "graph",
     "description": "Approximate size of active memtable (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L799",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_active_mem_table{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache capacity",
     "type": "graph",
     "description": "The block cache capacity per column family",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_capacity{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache usage",
     "type": "graph",
     "description": "The current usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_usage{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache usage {{partition}}"
      }
     ]
    },
    {
     "title": "Pinned block cache usage",
     "type": "graph",
     "description": "The current pinned usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_pinned_usage{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} pinned cache {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of live SST files",
     "type": "graph",
     "description": "Total size (bytes) of all SST  files belong to the latest LSM tree.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L882",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_live_sst_files_size{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  live sst {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of all SST files",
     "type": "graph",
     "description": "Total size (bytes) of all SST files.\n\nWARNING: may slow down online queries if there are too many files.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L878",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_total_sst_files_size{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  total sst {{partition}}"
      }
     ]
    },
    {
     "title": "Write stopped",
     "type": "table-old",
     "description": "Return 1 if write has been stopped.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L908",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_is_write_stopped{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  stopped write {{partition}}"
      }
     ]
    },
    {
     "title": "Actual write delay rate",
     "type": "graph",
     "description": "The current actual delayed write rate. 0 means no delay.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L905",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_writes_actual_delayed_write_rate{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}  delayed write {{partition}}"
      }
     ]
    },
    {
     "title": "Number of entries in immutable mem Tables",
     "type": "graph",
     "description": " Return sum of number of entries in all the immutable mem tables.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_num_entries_imm_mem_tables{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Running flush",
     "type": "graph",
     "description": "Returns the number of currently running flushes.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L783",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_flushes{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  flush {{partition}}"
      }
     ]
    },
    {
     "title": "Running compactions",
     "type": "graph",
     "description": "The number of currently running compactions.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L791",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_compactions{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  compaction {{partition}}"
      }
     ]
    },
    {
     "title": "Table Reader Memory ",
     "type": "graph",
     "description": "Returns estimated memory used for reading SST tables, excluding memory used in block cache (e.g., filter and index blocks).\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L832",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_estimate_table_readers_mem{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Table Reader {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Memory Size)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_elasticsearch_exporter_bulk_memory_size{namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch disk usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Start up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 },
   "collapsed": true,
   "panels": [
    {
     "title": "Atomix Partition Server Startup time",
     "type": "bargauge",
     "description": "Time taken to start and bootstrap partition servers.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "atomix_partition_server_startup_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": " Start {{pod}} p{{partition}}"
      },
      {
       "expr": "atomix_partition_server_bootstrap_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Bootstrap  {{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Atomix Partition Server Startup time",
     "type": "bargauge",
     "description": "Time taken to start and bootstrap partition servers.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "atomix_partition_server_startup_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": " Start {{pod}} p{{partition}}"
      },
      {
       "expr": "atomix_partition_server_bootstrap_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Bootstrap  {{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Atomix Partition Server Startup time",
     "type": "bargauge",
     "description": "Time taken to start and bootstrap partition servers.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "atomix_partition_server_startup_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": " Start {{pod}} p{{partition}}"
      },
      {
       "expr": "atomix_partition_server_bootstrap_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Bootstrap  {{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Streamprocessor Recovery Time",
     "type": "bargauge",
     "description": "Time taken to recover and reprocess events",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "zeebe_stream_processor_startup_recovery_time{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    }
   ]
  }
 ]
}