//import http from 'k6/http';
//import { check } from 'k6';
//
//export let options = {
//  stages: [
//    { target: 200, duration: '30s' },
//    { target: 0, duration: '30s' },
//  ],
//};
//
//export default function () {
//  const result = http.get('https://test-api.k6.io/public/crocodiles/');
//  check(result, {
//    'http response status code is 200': result.status === 200,
//  });
//}

// Auto-generated by the postman-to-k6 converter
// Auto-generated by the postman-to-k6 converter

//import "./libs/shim/core.js";
//
//export let options = { maxRedirects: 4 };
//
//const Request = Symbol.for("request");
//postman[Symbol.for("initial")]({
//  options,
//});
//
//export default function () {
//  postman[Request]({
//    name: "message-gateway sms API",
//    id: "0c5834c9-468c-4a33-961d-f1e2278ac61a",
//    method: "POST",
//    address: "https://messagegateway.sandbox.fynarfin.io/sms",
//    data: '[\n    {\n        "internalId": "20",\n        "mobileNumber": "+15005550012",\n        "message": "Random Message",\n        "providerId": 2\n    }\n]',
//    headers: {
//      "Fineract-Platform-TenantId": "default",
//      "Fineract-Tenant-App-Key": "123456543234abdkdkdkd",
//      "X-CorrelationID": "1234567868976798",
//      "Content-Type": "application/json",
//    },
//  });
//}/Users/dhavalmaniyar/Documents/projects/k6-helm-chart/k6-operator/e2e/test.js
import http from 'k6/http';
export const options = {
  insecureSkipTLSVerify: true,
  vus: 40,
  iterations: 300,
};
export default function () {
  const url = 'http://localhost:9191/sms';
  const payload = JSON.stringify([{
          "internalId": "20",
          "mobileNumber": "+15005550013",
          "message": "Random Message",
          "providerId": 2
  }]);

  const params = {
    headers: {
      "Fineract-Platform-TenantId": "default",
      "Fineract-Tenant-App-Key": "123456543234abdkdkdkd",
      "X-CorrelationID": "1234567868976798",
      "Content-Type": "application/json",
    },
  };
  http.post(url, payload, params);
}