ph-ee-engine:
  zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe-cluster-helm:
    global:
      elasticsearch:
        host: "ph-ee-elasticsearch"
    image:
      repository: camunda/zeebe
      tag: 1.1.0

    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    JavaOpts: "-Xms8g -Xmx8g -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal"

    elasticsearch:
      enabled: false
    kibana:
      enabled: false

  zeebe-operate-helm:
    enabled: true
    image:
      repository: camunda/operate
      tag: 1.1.0

  elasticsearch:
    enabled: true

  kibana:
    enabled: true
   
  operations:
    enabled: true

  operationsmysql:
    enabled: true

  ph_ee_connector_ams_mifos:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-ams"
    imageTag: latest

  ph_ee_connector_mojaloop:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-mojaloop"
    imageTag: "latest"

  kafka:
    enabled: true

  channel:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-channel"
    imageTag: latest
    
  operations_app:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-ops-bk"
    imageTag: "latest"
   
  operations_web:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-ops-web"
    imageTag: "latest"

  ph_ee_connector_gsma:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-gsma"
    imageTag: latest
  
  ph_ee_connector_slcb:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-slcb"
    imageTag: latest
    
  mpesa:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-mpesa"
    imageTag: latest
  
  roster_connector:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-roster"
    imageTag: latest

  paygops_connector:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-connector-ams-paygops"
    imageTag: latest

  notifications:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-notifications"
    imageTag: latest
   
  connector_bulk:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-bulk-processor"
    imageTag: latest

  zeebe_ops:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-zeebe-ops"
    imageTag: latest

  messagegateway:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-message-gateway"
    imageTag: latest
 
  importer_es:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-es-importer"
    imageTag: latest

  importer_rdbms:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-importer-rdbms"
    imageTag: latest

  kong:
    enabled: true
    image:
      repository: revomatico/docker-kong-oidc
      tag: "latest"

  keycloak:
    enabled: true
  
zeebe-operate:
    enabled: true
 
mock-oracle:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/mock-asl-oracle"
  imagePullPolicy: "Always"


