ph-ee-superset:
  ph-ee-engine:

    # zeebe-operate-helm:

    # elasticsearch:

    # kibana:

    # operations:

    ph_ee_connector_ams_mifos:
      imageTag: "v1.2.1"

    ph_ee_connector_mojaloop:
      imageTag: "latest"

    # kafka:

    channel:
      imageTag: "v1.4.1"


    operations_app:
      imageTag: "v1.3.0"

    operations_web:
      imageTag: "v1.3.1"

    ph_ee_connector_gsma:
      imageTag: "v1.0.2"

    ph_ee_connector_slcb:
      imageTag: "v1.1.1"

    mpesa:
      imageTag: "v1.3.1"

    roster_connector:
      imageTag: "v1.2.0"

    paygops_connector:
      imageTag: "v1.5.0"

    notifications:
      imageTag: "v1.0.2"

    connector_bulk:
      imageTag: "v1.4.1"

    zeebe_ops:
      imageTag: "v1.0.2"

    messagegateway:
      imageTag: "v1.0.0"

    importer_es:
      imageTag: "v1.3.0"

    importer_rdbms:
      imageTag: "v1.2.0"

    # kong:
  
    # zeebe-operate:

    # mock-oracle:

