apiVersion: v2
name: ph-ee-g2psandbox-fynarfin
description: PaymentHub EE Barebone Edition

type: application
version: 0.2.0
appVersion: 1.16.0

dependencies:
- name: ph-ee-g2psandbox
  repository: https://fynarfin.io/images/ph-ee-g2psandbox-1.2.0
  version: 1.2.0
