apiVersion: v2
name: ph-ee-g2psandbox-fynarfin
description: PaymentHub EE Barebone Edition

type: application
version: 1.6.0
appVersion: 1.6.0

dependencies:
- name: ph-ee-g2psandbox
  repository: https://fynarfin.io/images/ph-ee-g2psandbox-1.6.0
  version: 1.6.0
