jmeter:
  jmeter:
    master:
      resources:
        requests:
          memory: "512Mi"
          cpu: "128m"
        limits:
          memory: "1024Mi"
          cpu: "1024m"
    slave:
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "512m"

  grafana:
    ingress:
      enabled: true
      hostname: "grafana-jmeter.sandbox.fynarfin.io"
      path: "/"
      wildcardhostname: "*.sandbox.fynarfin.io"
      annotations:
        kubernetes.io/ingress.class: "nginx"
#        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    resources:
      requests:
        memory: "256Mi"
        cpu: "128m"
      limits:
        memory: "512Mi"
        cpu: "512m"

  influxdb:
    resources:
      requests:
        memory: "256Mi"
        cpu: "128m"
      limits:
        memory: "256Mi"
        cpu: "512m"

  demo:
    resources:
      requests:
        memory: "64Mi"
        cpu: "128m"
      limits:
        memory: "512Mi"
        cpu: "1024m"

  telegraf:
    resources:
      requests:
        memory: "256Mi"
        cpu: "256m"
      limits:
        memory: "256Mi"
        cpu: "256m"

  wiremock:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"



