ph-ee-g2psandbox:
  ph-ee-engine:

    zeebe-cluster-helm:
      enabled: true

      elasticsearch:
        enabled: true
      kibana:
        enabled: true

    zeebe-operate-helm:
      ingress:
        enabled: false
        host: operate-ns.sandbox.fynarfin.io

    kibana:
      ingress:
        enabled: true
        className: "nginx"
        pathtype: "Prefix"
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        hosts:
        - host: analytics-ns.sandbox.fynarfin.io
          paths:
          - path: /

    operations:

    ph_ee_connector_ams_mifos:
      enabled: true
      imageTag: v1.2.2
      deployment:
        annotations:
          rollme: '{{ randAlphaNum 5 | quote }}'
      ams_local_interop_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_account_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_customer_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_auth_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_loan_host: "https://fynams.sandbox.fynarfin.io/"
      ingress:
        enabled: true
        hosts:
        - host: ams-mifos-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: ph-ee-connector-ams-mifos
                port:
                  number: 80
        - host: ams-mifos-mock-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: ph-ee-connector-ams-mifos
                port:
                  number: 7070

    ph_ee_connector_mojaloop:
      enabled: true
      imageTag: "830df54849"
      ingress:
        enabled: false
        hosts:
        - host: mojaloop-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: ph-ee-connector-mojaloop-java
                port:
                  number: 80

    kafka:
      nodePort: 30093

    channel:
      enabled: true
      operations:
        url: "http://ops-bk-ns.sandbox.fynarfin.io/api/v1"
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: false
        hosts:
        - host: channel-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-connector-channel"
                port:
                  number: 8443
        - host: channel-gsma-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-connector-channel-gsma"
                port:
                  number: 82


    operations_app:
      enabled: true
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: false
        hosts:
        - host: ops-bk-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-operations-app"
                port:
                  number: 80

    operations_web:
      enabled: true
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: ops-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-operations-web"
                port:
                  number: 4200

    ph_ee_connector_gsma:
      enabled: true
      ingress:
        enabled: false

    ph_ee_connector_slcb:
      enabled: false

    mpesa:
      enabled: false

    roster_connector:
      enabled: false

    paygops_connector:
      enabled: false

    notifications:
      enabled: true
      NOTIFICATION_FAILURE_ENABLED: "false"
      ingress:
        enabled: false
        hosts:
        - host: notifications-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-connector-notifications"
                port:
                  number: 80

    connector_bulk:
      enabled: true
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      aws:
        region: "ap-south-1"
        access_key: "aws-access-key"
        secret_key: "aws-secret-key"
      operations_app:
        contactpoint: "https://ops-bk-ns.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"
      identity_account_mapper:
        hostname: "https://identity-mapper-ns.sandbox.fynarfin.io"
      ingress:
        enabled: false
        className: "kong"
        tls:
        - secretName: sandbox-secret
        hosts:
        - host: bulk-connector-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-connector-bulk"
                port:
                  number: 80

    zeebe_ops:
      enabled: true
      tenants: "rhino,gorilla"
      ingress:
        enabled: false
        hosts:
        - host: zeebeops-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-zeebe-ops"
                port:
                  number: 80

    messagegateway:
      enabled: true
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      ingress:
        enabled: false
        hosts:
        - host: messagegateway-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "message-gateway"
                port:
                  number: 80

    importer_es:
      enabled: true

    importer_rdbms:
      enabled: true

    mockpayment:
      enabled: true
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - host: mockpaymentschema-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-connector-mock-payment-schema"
                port:
                  number: 8080

    wildcardhostname: "*-ns.sandbox.fynarfin.io"
    tls: ""

    keycloak:
      enabled: false
      ingress:
        enabled: false
        rules:
        - host: 'keycloak-ns.sandbox.fynarfin.io'
          paths:
          - path: /
            pathType: Prefix


    kong:
      enabled: false
      ingress:
        enabled: false
        hostname: admin-kong-ns.sandbox.fynarfin.io

    redis:
      enabled: true
      replica:
        replicaCount: 0

    vouchers:
      enabled: true

      voucher:
        hostname: "https://vouchers-ns.sandbox.fynarfin.io"

      salting:
        enabled: true

      identity-account-mapper:
        hostname: "https://identity-mapper-ns.sandbox.fynarfin.io"
      operations:
        hostname: "https://ops-bk-ns.sandbox.fynarfin.io"
        endpoints:
          transfers: "/api/v1/transfers?size=1&page=0"

      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
        - secretName: sandbox-secret
        hosts:
        - host: vouchers-ns.sandbox.fynarfin.io
          paths:
          - path: "/"
            backend:
              service:
                name: "ph-ee-vouchers"
                port:
                  number: 80


  account_mapper:
    enabled: true
    deployment:
      annotations:
        rollme: "{{ randAlphaNum 5 | quote }}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
      - secretName: sandbox-secret
      hosts:
      - host: identity-mapper-ns.sandbox.fynarfin.io
        paths:
        - path: "/"
          backend:
            service:
              name: "ph-ee-identity-account-mapper"
              port:
                number: 80

