apiVersion: v1
name: ph-ee-kenya
description: PaymentHub EE Barebone Edition
type: application
version: 0.0.0
appVersion: 0.0.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-0.0.0-SNAPSHOT
  version: 0.0.0-SNAPSHOT