ph-ee-superset:
  ph-ee-engine:
    
    operations_web:
      imageTag: "v1.3.1"

    zeebe-operate-helm:
       enabled: false

    elasticsearch:
       enabled: false

    # kibana:

    operations:
       enabled: false

    ph_ee_connector_ams_mifos:
      enabled: false

    ph_ee_connector_mojaloop:
      enabled: false

    kafka:
      enabled: false

    channel:
      enabled: false

    operations_app:
      enabled: false

    ph_ee_connector_gsma:
      enabled: false

    ph_ee_connector_slcb:
      enabled: false

    mpesa:
      enabled: false

    roster_connector:
      enabled: false

    paygops_connector:
      enabled: false

    notifications:
      enabled: false

    connector_bulk:
      enabled: false

    zeebe_ops:
      enabled: false

    messagegateway:
      enabled: false

    importer_es:
      enabled: false

    importer_rdbms:
      enabled: false

    # kong:
  
    # zeebe-operate:

    # mock-oracle:
      
fin-engine:
 
  #communityapp:

  fineract:
    enabled: false
    
operations: 

  # grafana:
    