apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in02tn03-ph-ee-connector-mojaloop-java
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: in02tn03.mifos.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ph-ee-connector-mojaloop-java
                port:
                  number: 80            
